### ISSUE TITLE
Module is not loading with FVTT 11.308, DnD 2.3.1 and Sequencer 3.1.4 with the Forge

### ISSUE THREAD

**Issue by franckflo** [Autumn225/universal-animations#2]
Hi, I'd love to try your module, but the module is not showing in my world after installing it. It's not visible in the Module Manager to enable. Let me know if you need more information.

FVTT 11.308 
DnD 2.3.1
Sequencer 3.1.4

**Comment by Autumn225** [comment]
Fixed in the new release.

**Comment by franckflo** [comment]
Thanks!
