### ISSUE TITLE
Getting firearm hook error on every attack

### ISSUE THREAD

**Issue by ctbritt** [Autumn225/universal-animations#4]
Thought the "fir" property was a typo but seeing it is a firearm property. But getting this error:

![CleanShot 2023-11-15 at 14 14 53@2x](https://github.com/Autumn225/universal-animations/assets/4516034/572e75ab-8a7d-4310-b7ab-73b97ea5b59e)

**Comment by Autumn225** [comment]
Looks like I forgot some null checks on that line, I'll fix it today.

**Comment by Autumn225** [comment]
Should be fixed now, let me know if theres anything else I didn't catch.
